drivers: mediatek: c2k_usb fix implicit truncation to a one-bit wide bit-field constant conversion
A one-bit signed bit-field can only hold the values 0 and -1; this
corrects the diagnostic behavior accordingly.

../drivers/misc/mediatek/c2k_usb/f_rawbulk.c:345:16: error: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Werror,-Wsingle-bit-bitfield-constant-conversion]
        fn->activated = 1;
                      ^ ~
../drivers/misc/mediatek/c2k_usb/f_rawbulk.c:390:19: error: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Werror,-Wsingle-bit-bitfield-constant-conversion]
                fn->initialized = 1;
                                ^ ~
../drivers/misc/mediatek/c2k_usb/f_rawbulk.c:470:19: error: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Werror,-Wsingle-bit-bitfield-constant-conversion]
                fn->initialized = 1;
                                ^ ~
3 errors generated.

Signed-off-by: Masalief Maulana <masaliefmaulana@proton.me>
Tested-by: Masalief Maulana <masaliefmaulana@proton.me>
(cherry picked from commit 16f9cc73308ad1a580e9b44888752e32fde35073)