drivers: gpu: mali-r32p1: fix function prototype warning
../drivers/gpu/mediatek/gpu_mali/mali_valhall/mali-r32p1/drivers/gpu/arm/midgard/platform/mtk_platform_common/mtk_mfg_counter.c:772:23: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int gator_gpu_pmu_init()
                      ^
                       void

Change-Id: I1bad9edc1e321f41b09ae573079dfd79c2ca7ee1
Signed-off-by: CloudedQuartz <ayan.pande06@gmail.com>
(cherry picked from commit ecf01c85ee13be559c3c5f3b8a2e9e1a30272091)